In [1]:
import numpy as np # to create tictac empty board
import random
from time import sleep

# Creating an empty tic-tac-toe board
def empty_board():
    board = np.array([
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ])
    return board

# Check for empty places on the board
def empty_places(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j] == 0:
                l.append((i, j))
    return l

# Select a random place for the player on the tic-tac-toe board
def random_place(board, player):
    select = empty_places(board)
    current_loc = random.choice(select)
    board[current_loc] = player
    return board

# Check the horizontal rows for a winner
def row_winner(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
        if win == True:
            return win
    return False

# Check the vertical columns for a winner
def col_winner(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
        if win == True:
            return win
    return False

# Check the diagonal rows for a winner
def diag_winner(board, player):
    win = True
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win

    win = True
    for x in range(len(board)):
        y = len(board) - 1 - x
        if board[x, y] != player:
            win = False
    return win

# Evaluate whether there is a winner or a tie
def evaluate_game(board):
    # Winner {0= indecisive, 1= Player 1; 2 = Player 2; -1 = Tie}
    winner = 0
    for player in [1, 2]:
        if row_winner(board, player) or col_winner(board, player) or diag_winner(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

# Main function to run/start the game
def tic_tac_toe():
    board = empty_board()
    winner = 0
    counter = 1
    print(board)
    sleep(2)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate_game(board)
            if winner != 0:
                break
    return winner

# Driver code
print("Winner is player: " + str(tic_tac_toe()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Board after 2 move
[[0 2 0]
 [0 0 0]
 [0 0 1]]
Board after 3 move
[[1 2 0]
 [0 0 0]
 [0 0 1]]
Board after 4 move
[[1 2 2]
 [0 0 0]
 [0 0 1]]
Board after 5 move
[[1 2 2]
 [0 0 1]
 [0 0 1]]
Board after 6 move
[[1 2 2]
 [0 2 1]
 [0 0 1]]
Board after 7 move
[[1 2 2]
 [0 2 1]
 [0 1 1]]
Board after 8 move
[[1 2 2]
 [0 2 1]
 [2 1 1]]
Winner is player: 2
